### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by tyrone-sudeium** [hamin/FayeSwift#1]
Great looking library you've got here!

Long ago I worked on a Faye implementation for Objective-C, which was also based on the work of @pcrawfor, adding many interesting features which a full-featured Faye Client would want to have.

If you'd like some inspiration for what additional features to add to this project over time, check it out:
https://github.com/tyrone-sudeium/FayeObjC

I added things like:
* Block (closure) based message handlers
* Wildcard channel support
* Long-polling support
* Data preprocessors (allows you to catch and modify every incoming and outgoing data packet)

**Comment by shams-ahmed** [comment]
Blocked based approach would be great!

**Comment by hamin** [comment]
@shams-ahmed the library currently already does support a block based api as well as a delegate api
