### ISSUE TITLE
Add Cocoapods support

### ISSUE THREAD

**Issue by hamin** [hamin/FayeSwift#10]

**Comment by shams-ahmed** [comment]
@hamin was you able to add support for pod, i saw you got podspec in project!

**Comment by hamin** [comment]
@shams-ahmed I haven't published the Pod yet to cocoa pods. But if you don't mind testing linking to the Podspec directly in your Podfile and see how it works that would be great.

**Comment by shams-ahmed** [comment]
@hamin will do tomorrow!

**Comment by shams-ahmed** [comment]
@hamin sorry for the delay it working fine

**Comment by shams-ahmed** [comment]
@hamin actually it not working, you need to do a git tag with 0.1.0

**Comment by hamin** [comment]
@shams-ahmed this is done. Going to close this issue.

**Comment by hamin** [comment]
https://cocoapods.org/pods/FayeSwift
