### ISSUE TITLE
Should faye response be in its own model object?

### ISSUE THREAD

**Issue by shams-ahmed** [hamin/FayeSwift#13]

**Comment by hamin** [comment]
@shams-ahmed just getting back to this. I think that would be nice PR welcome :)

**Comment by shams-ahmed** [comment]
@hamin i've made quite a few modification and fixed few issues, https://github.com/shams-ahmed/FayeSwift/tree/feature/customSubscribe


i can clean this up and send a pull request

**Comment by hamin** [comment]
@shams-ahmed lets do it :)

**Comment by shams-ahmed** [comment]
@hamin let me clean few things up first, i should be able to make a PR in few days...

**Comment by hamin** [comment]
i think this issue has been resolved by #20
