### ISSUE TITLE
Supporting Swift 3

### ISSUE THREAD

**Issue by dmdque** [hamin/FayeSwift#23]
Are there any plans to make this available with Swift 3?

**Comment by shams-ahmed** [comment]
@dmdque am longer doing much work with Faye.. but am sure if you submitted a pull request @hamin could look at merging it.

**Comment by hamin** [comment]
@dmdque i'm in the same boat as @shams-ahmed happy to look at a PR, if not will probably get around to it soon.

**Comment by linkthrow** [comment]
@dmdque Hey pal, did you manage to convert this to Swift 3?

**Comment by dmdque** [comment]
@linkthrow In the end I used a different solution. [Phoenix](https://github.com/phoenixframework/phoenix) with [BirdSong](https://github.com/sjrmanning/Birdsong)

**Comment by hamin** [comment]
@dmdque @linkthrow Sorry about the delay. I just pushed version `0.3.0` to cocoa pods with Swift 3 support
