### ISSUE TITLE
Unsubscribe doesn't remove channel from openSubscriptions and pendingSubscriptions

### ISSUE THREAD

**Issue by mtutunik** [hamin/FayeSwift#8]
The method unsubscribeFromChannel(channel:String) doesn't remove channel entry from openSubscriptions and pendingSubscriptions maps. Therefrom if you do unsubscribeFromChannel and later subscribeToChannel the later will do nothing since it has a check:

if(self.isSubscribedToChannel(channel) || self.pendingSubscriptions.containsObject(channel) ){
     return
}

BTW, some debug message before return can be helpful as well.

I believe unsubscribeFromChannel should look something like this:

func unsubscribeFromChannel(channel:String){
        self.queuedSubscriptions.removeObject(channel)
        self.unsubscribe(channel)
        self.channelSubscriptionBlocks[channel] = nil;
        self.openSubscriptions.removeObject(channel)
        self.pendingSubscriptions.removeObject(channel)
    }

**Comment by hamin** [comment]
@mtutunik great find :). Stay tuned as I have some more pending work on this lib that I'll be pushing out soon
